blank_issues_enabled: false
contact_links:
  - name: Ask a question or suggest a feature
    url: https://github.com/farm-companion/farm-frontend/discussions
    about: Use Discussions for general ideas and Q&A.
